config/routes.rb
CustomeVisit::Application.routes.draw do
  
   root :to => 'visits#index'

  resources :visits

  resource :user, :controller => "user" do
    member do
      post 'manageUser'
    end
  end

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  devise_for :users

 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :role, :remember_me
end

app/models/visit.rb
class Visit < ActiveRecord::Base
attr_accessible :attachment
attr_accessible :Agenda
attr_accessible :Description
attr_accessible :time
attr_accessible :customers


attr_accessor :attachment


has_attached_file :attachment

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def new
    @user = User.new
   
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>



    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Client Visit Portal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

   <%= stylesheet_link_tag "application", "colorbox", "jquery-ui-1.9.2.custom", :media => "all" %>


    <link href="images/favicon.ico" rel="shortcut icon">

    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

    <style>
      ul.nav li.dropdown:hover ul.dropdown-menu{
        display: block;
      }
      body{
        padding: 40px 0 40px 0;
      }

    </style>
  </head>
  <body>

    <%= render 'shared/header' %>
    </br>
    </br>
    <div class="container-fluid">



      <div class="notice hide" id="devise_notice"><%= notice%></div>
      <div class="alert hide" id="devise_alert"><%=  alert%></div>





      
      <div class="span10" style="min-height: 650px; width:72%">
        <%= yield %>
      </div>

    </div> <!-- /container -->

  <footer class="offset5">
    &copy; 2010-2013 Tata Consultancy Services Limited.  All Rights Reserved 
  </footer>

  <footer class="offset7">
    <%= image_tag "icon-tata.png" %>
  </footer>


  <!-- Javascripts
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag "application","app", "jquery.colorbox","jquery-ui-1.9.2.custom.min"%>

</body>
</html>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner" style="height:60px">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" style="margin-top: 5px;"><h1><font color= "white">Client Visit Portal</font></h1></a>
      <div class="pull-right"  style="margin-top: 5px;">
        <% if user_signed_in? %>
          <div class="pull-right">
            <b><font color= "white" size="2px">
                Today is <%=Time.new.strftime('%a %d %b %Y')%>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </b></font>
                </div>
                <div class="nav-collapse">
                  <ul class="nav">
                    <li class="active"></li>

                    <li class="dropdown">
                      <a href="#"
                         class="dropdown-toggle"
                         data-toggle="dropdown"> <b><font color= "white" size="2px">
                        Welcome, <%= current_user.email %></b></font>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                         <li><%= link_to 'Home', visits_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                        <li class="divider"></li>
                        <li> <%= link_to "Sign out", destroy_user_session_path , :method => :delete%> </li>
                      </ul>
                    </li>

                  </ul>
                </div><!--/.nav-collapse -->

              <% end %>
         
        </div>


      </div>
    </div>
  </div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<head>
<h2>Manage User</h2>
</head>
<body>


      <div >
        <h1> Add New User </h1>
         <%= form_for @user, :url => user_index_path do |f| %>
          <div><br><b><font size="3px">Email</b></font><br>
            <%= f.text_field :email %></div><br>

          <div><b><font size="3px">Password </b></font><br>
            <%= f.password_field :password, :autocomplete => "off" %></div><br>

          <div><b><font size="3px">Confirm Password</b></font><br>
            <%= f.password_field :password_confirmation %></div><br>

          <div><b><font size="3px">Role</b></font><br>
          <b><%= f.radio_button :role , 'Member',:checked => true %> Member
            <br><%= f.radio_button :role, 'Admin'%> Admin
          </b>
         </div><br>
         <br>

          <div><%= f.submit "Save", :class=> 'btn btn-primary' %></div> <%end%>

      </div>


</body>

app/views/visits/_form.html.erb
<%= form_for(@visit, :html => {:multipart => true}) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div style="height: 50px">
</div>

  <div class="field">
    <%= f.label :Agenda , "Agenda:"%>
    <%= f.text_field :Agenda %>
  </div>

  <div class="field" >
    <%= f.label :Description, "Description:" %>
    <%= f.text_field :Description %>
  </div>

<div class="field" id="Date">
  <%= f.label :time, "Date:" %>
  <%= f.text_field :time %>
</div>



  <div class="field">
    <%= f.label :customers, "Customers:" %>
    <%= f.text_field :customers %>
  </div>


<div class="field">
    <%= f.label :attachment, "Attachment:" %>
    <%= f.file_field :attachment %>
  </div>

 

<div style="height: 50px">
</div>

<div>  <%= f.submit "Save", :class=> 'btn btn-primary' %></div>



<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h2>Listing visits</h2>

  <div style="height: 50px">
  </div>




<div style="min-width: 960px; overflow:auto;">
    <table  id="index_table" >
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Agenda </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Description </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 100px "><b>Time </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Customers </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Agenda Sheet </b></td>
        </tr>
      </thead>
      
    <% @visits.each do |visit| %>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= visit.Agenda %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= visit.Description %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 100px "><%= visit.time %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= visit.customers %></td>

        <%  if visit.attachment.blank? %>
            <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px ">Not Available</td>
        <% else %>
            <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= link_to(image_tag("Download.png", :border => 0), visit.attachment.url)%></td>
        <% end %>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><b><%= link_to 'Show', visit %></b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><b><%= link_to 'Edit', edit_visit_path(visit) %></b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><b><%= link_to 'Destroy', visit, confirm: 'Are you sure?', method: :delete %></b></td>
        </tr>
        <% end %>
    </table>
  </div>


  <div style="height: 50px">
  </div>

<div class= 'btn btn-info'>
<font size="3" color=#FFFFFF>
<%= link_to 'New Visit', new_visit_path, :style => 'text-decoration: none'  %>
</font>
</div>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>


<div class= 'btn btn-info'>
<font color=#FFFFFF>
<%= link_to 'Back', visits_path %>
</font>
</div>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>
<p>

<div style="min-width: 960px; overflow:auto;">
    <table  id="show_table" >
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Agenda </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Description </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Time </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 70px "><b>Customers </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><b>Agenda Sheet </b></td>
        </tr>
      </thead>

        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><%= @visit.Agenda %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @visit.Description %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= @visit.time %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 70px "><%= @visit.customers %></td>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 150px "><%= link_to(image_tag("Download.png", :border => 0), @visit.attachment.url)%></td>



 

        </tr>
    </table>
  </div>




  <div style=" min-height: 50px">
  </div>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>